# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Noticia',
        ),
    ]
