# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20160226_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(default=None, upload_to='webusac/noticias/static/noticias/images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
