# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_remove_noticia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, upload_to='webusac/noticias/static/noticias/images/%Y/%m/%d'),
        ),
    ]
