# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_noticia_otro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='otro',
        ),
    ]
