# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_noticia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, upload_to='noticias/images_upload/%Y/%m/%d'),
        ),
    ]
