# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_auto_20160229_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_upload/%Y/%m/%d'),
        ),
    ]
