# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_auto_20160301_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, default='images_upload/logo2.png', upload_to='images_upload/%Y/%m/%d'),
        ),
    ]
