# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_auto_20160302_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='university',
            field=models.CharField(default='No universidad', max_length=250),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='year',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
