# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0019_auto_20160302_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ('-year',)},
        ),
    ]
