# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0020_auto_20160303_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='noticias.Anho')),
            ],
        ),
        migrations.CreateModel(
            name='T_Beca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='beca',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='noticias.T_Beca'),
        ),
    ]
