# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0021_auto_20160307_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_beca',
            name='type',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=13),
        ),
    ]
