# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_auto_20160307_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=True)),
                ('carnet_number', models.BooleanField(default=True)),
                ('degree', models.BooleanField(default=True)),
                ('phone', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('unity', models.BooleanField(default=True)),
                ('average', models.BooleanField(default=True)),
                ('credit', models.BooleanField(default=True)),
                ('notes', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='beca',
            name='attach',
            field=models.FileField(default='a', upload_to='PDF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beca',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beca', to='noticias.Formulario'),
            preserve_default=False,
        ),
    ]
