# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_auto_20160307_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='attach',
            field=models.FileField(default='a', upload_to='PDF'),
            preserve_default=False,
        ),
    ]
