# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0023_auto_20160310_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='type',
            field=models.CharField(default='Base', max_length=100),
            preserve_default=False,
        ),
    ]
