# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0024_formulario_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Beca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('carnet_number', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=250)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('unity', models.BooleanField(default=True)),
                ('average', models.FloatField()),
                ('credit', models.FloatField()),
                ('notes', models.TextField()),
                ('beca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='noticias.Beca')),
            ],
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='type',
            new_name='name_form',
        ),
    ]
