# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0025_auto_20160314_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
