# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0026_beca_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
