# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0027_auto_20160315_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='average',
            new_name='apoyo_familiar',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='carnet_number',
            new_name='calusac',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='credit',
            new_name='calusac_ult_niv',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='degree',
            new_name='carrera',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='name',
            new_name='casa',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='notes',
            new_name='creditos',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='phone',
            new_name='departamento_vive',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='unity',
            new_name='edad',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='average',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='carnet_number',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='datos_beca',
            name='unity',
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='apoyo_familiar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='calusac',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='calusac_ult_niv',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='carrera',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='casa',
            field=models.CharField(blank=True, choices=[('propia', 'Propia'), ('alquilada', 'Alquilada'), ('casa de huespedes', 'Casa de Huespedes'), ('de familiares', 'De Familiares')], max_length=20),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='creditos',
            field=models.FloatField(blank=True, default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='departamento_vive',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='edad',
            field=models.PositiveIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='escuela_vac_ant',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='escuela_vac_ant_curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='escuela_vac_ant_fecha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='laboratorio',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='n_carne',
            field=models.PositiveIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='n_colegiado',
            field=models.PositiveIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='n_hermanos',
            field=models.PositiveSmallIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='n_reg_personal',
            field=models.PositiveIntegerField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='niv_ingl',
            field=models.CharField(blank=True, choices=[('basico', 'Basico'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=10),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='nombre_curso_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='nombre_curso_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='profesion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='promedio',
            field=models.FloatField(blank=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='recibe_ayuda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='salario',
            field=models.FloatField(blank=True, default='12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='secc_curso_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='secc_curso_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='sosten_estudios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='status',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('profesional', 'Profesional')], max_length=12),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='telefono',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='trabaja_ing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='trabaja_usac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='trabaja_usac_lugar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='trabajo_padres',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='transporte',
            field=models.CharField(blank=True, choices=[('vehiculo', 'Vehiculo'), ('bus', 'Bus'), ('moto', 'Moto'), ('a pie', 'A Pie')], max_length=20),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='unidad_trabajo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='zona_vive',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='escuela_vac_ant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='escuela_vac_ant_curso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='escuela_vac_ant_fecha',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='laboratorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='lugar_trabajo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='n_carne',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='n_colegiado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='n_hermanos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='n_reg_personal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='niv_ingl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_completo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_curso_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='nombre_curso_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='profesion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='promedio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='recibe_ayuda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='salario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='secc_curso_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='secc_curso_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='sosten_estudios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='telefono',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='trabaja_ing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='trabaja_usac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='trabaja_usac_lugar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='trabajo_padres',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='transporte',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='unidad_trabajo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='zona_vive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
