# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0028_auto_20160316_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_beca',
            name='calusac',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='casa',
            field=models.CharField(blank=True, choices=[('propia', 'Propia'), ('alquilada', 'Alquilada'), ('casa de huespedes', 'Casa de Hu\xe9spedes'), ('de familiares', 'De Familiares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='escuela_vac_ant',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='laboratorio',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='niv_ingl',
            field=models.CharField(blank=True, choices=[('basico', 'B\xe1sico'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=10),
        ),
    ]
