# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0033_auto_20160317_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_beca',
            name='creditos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
