# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0034_auto_20160317_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_beca',
            name='n_carne',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_colegiado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_hermanos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_reg_personal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='promedio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
