# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0035_auto_20160317_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datos_beca',
            unique_together=set([('beca', 'n_carne')]),
        ),
    ]
