# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0036_auto_20160317_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_beca',
            name='beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='noticias.Beca'),
        ),
    ]
