# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0037_auto_20160317_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('adjunto', models.FileField(upload_to='MasInfo')),
            ],
        ),
        migrations.AddField(
            model_name='beca',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='adjunto1',
            field=models.FileField(blank=True, upload_to='Adjuntos_Beca'),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='adjunto2',
            field=models.FileField(blank=True, upload_to='Adjuntos_Beca'),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='anho',
            field=models.CharField(blank=True, choices=[('Junio 2010', 'Junio 2010'), ('Junio 2011', 'Junio 2011'), ('Diciembre 2010', 'Diciembre 2010'), ('Diciembre 2011', 'Diciembre 2011')], max_length=15),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='beneficiado',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='conv_ant',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='conv_ant_cual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='conv_ant_exp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='dpi',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='estudios_completos',
            field=models.CharField(blank=True, choices=[('licenciatura', 'Licenciatura'), ('especialidad', 'Especialidad'), ('maestr\xeda', 'Maestr\xeda'), ('doctorado', 'Doctorado')], max_length=12),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='exp_lab',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=9),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='datos_beca',
            name='tit_acred',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='adjunto1',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='adjunto2',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='anho',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='beneficiado',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='conv_ant',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='conv_ant_cual',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='conv_ant_exp',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='dpi',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='estudios_completos',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='exp_lab',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='genero',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='pasaporte',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tit_acred',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='universidad',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='noticias.Pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beca',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Ingenier\xeda Civil', 'Ingenier\xeda Civil'), ('Ingenier\xeda Quimica', 'Ingenier\xeda Quimica'), ('Ingenier\xeda Industrial', 'Ingenier\xeda Industrial'), ('Ingenier\xeda El\xe9ctrica', 'Ingenier\xeda El\xe9ctrica'), ('Ingenier\xeda Mec\xe1nica', 'Ingenier\xeda Mec\xe1nica'), ('Ingenier\xeda Mec\xe1nica El\xe9ctrica', 'Ingenier\xeda Mec\xe1nica El\xe9ctrica'), ('Ingenier\xeda Mec\xe1nica Industrial', 'Ingenier\xeda Mec\xe1nica Industrial'), ('Ingenier\xeda en Ciencias y Sistemas', 'Ingenier\xeda en Ciencias y Sistemas'), ('Ingenier\xeda Electr\xf3nica', 'Ingenier\xeda Electr\xf3nica'), ('Ingenier\xeda Ambiental', 'Ingenier\xeda Ambiental'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='apoyo_familiar',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='calusac',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='calusac_ult_niv',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='carrera',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='casa',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='creditos',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='departamento_vive',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='edad',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='escuela_vac_ant',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='escuela_vac_ant_curso',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='escuela_vac_ant_fecha',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='laboratorio',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='lugar_trabajo',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_carne',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_colegiado',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_hermanos',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_reg_personal',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='niv_ingl',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_completo',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_curso_1',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_curso_2',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='profesion',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='promedio',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='recibe_ayuda',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='salario',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='secc_curso_1',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='secc_curso_2',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='sosten_estudios',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='status',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabaja_ing',
            field=models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabaja_usac',
            field=models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabaja_usac_lugar',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabajo_padres',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='transporte',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='unidad_trabajo',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='zona_vive',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='datos_beca',
            unique_together=set([('beca', 'n_colegiado'), ('beca', 'n_carne'), ('beca', 'dpi')]),
        ),
    ]
