# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0038_auto_20160413_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='body',
            field=models.TextField(verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, default='images_upload/logo2.png', upload_to='images_upload/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='title',
            field=models.CharField(max_length=250, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='image',
            field=models.ImageField(upload_to='countries', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
