# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0039_auto_20160413_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anho',
            options={'verbose_name': 'A\xf1o'},
        ),
        migrations.AlterModelOptions(
            name='datos_beca',
            options={'verbose_name': 'Datos de las Becas', 'verbose_name_plural': 'Datos de las Becas'},
        ),
        migrations.AlterModelOptions(
            name='masinfo',
            options={'verbose_name': 'M\xe1s Info', 'verbose_name_plural': 'M\xe1s Info'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pa\xeds', 'verbose_name_plural': 'Pa\xedses'},
        ),
        migrations.AlterModelOptions(
            name='t_beca',
            options={'verbose_name': 'Tipo Beca', 'verbose_name_plural': 'Tipo Beca'},
        ),
        migrations.AlterModelOptions(
            name='universidad',
            options={'verbose_name': 'Universidad', 'verbose_name_plural': 'Universidades'},
        ),
        migrations.AlterField(
            model_name='anho',
            name='year',
            field=models.IntegerField(verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='attach',
            field=models.FileField(upload_to='PDF', verbose_name='Documento adjunto'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='noticias.Anho', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='date_end',
            field=models.DateField(verbose_name='Fecha de fin de la convocatoria'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='date_start',
            field=models.DateField(verbose_name='Fecha de inicio de la convocatoria'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='description',
            field=models.TextField(verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beca', to='noticias.Formulario', verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre de la beca'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='beca',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='noticias.T_Beca', verbose_name='Tipo de beca'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='anho',
            field=models.CharField(blank=True, choices=[('Junio 2010', 'Junio 2010'), ('Junio 2011', 'Junio 2011'), ('Diciembre 2010', 'Diciembre 2010'), ('Diciembre 2011', 'Diciembre 2011')], max_length=15, verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='apoyo_familiar',
            field=models.CharField(blank=True, max_length=100, verbose_name='\xbfQui\xe9nes apoyan al ingreso familiar?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='beneficiado',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2, verbose_name='Fue beneficiad@'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='calusac',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2, verbose_name='\xbfHa estudiado en CALUSAC?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='calusac_ult_niv',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nivel CALUSAC'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Ingenier\xeda Civil', 'Ingenier\xeda Civil'), ('Ingenier\xeda Quimica', 'Ingenier\xeda Quimica'), ('Ingenier\xeda Industrial', 'Ingenier\xeda Industrial'), ('Ingenier\xeda El\xe9ctrica', 'Ingenier\xeda El\xe9ctrica'), ('Ingenier\xeda Mec\xe1nica', 'Ingenier\xeda Mec\xe1nica'), ('Ingenier\xeda Mec\xe1nica El\xe9ctrica', 'Ingenier\xeda Mec\xe1nica El\xe9ctrica'), ('Ingenier\xeda Mec\xe1nica Industrial', 'Ingenier\xeda Mec\xe1nica Industrial'), ('Ingenier\xeda en Ciencias y Sistemas', 'Ingenier\xeda en Ciencias y Sistemas'), ('Ingenier\xeda Electr\xf3nica', 'Ingenier\xeda Electr\xf3nica'), ('Ingenier\xeda Ambiental', 'Ingenier\xeda Ambiental'), ('Otros', 'Otros')], max_length=50, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='casa',
            field=models.CharField(blank=True, choices=[('propia', 'Propia'), ('alquilada', 'Alquilada'), ('casa de huespedes', 'Casa de Hu\xe9spedes'), ('de familiares', 'De Familiares')], max_length=20, verbose_name='Su casa es:'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='conv_ant',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2, verbose_name='Ha participado en convocatorias anteriores'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='conv_ant_cual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Indicar cuales (Si aplica):'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='conv_ant_exp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Explicar en que consistia:'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='creditos',
            field=models.FloatField(blank=True, null=True, verbose_name='Cr\xe9ditos'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='departamento_vive',
            field=models.CharField(blank=True, max_length=200, verbose_name='En que departamento vive'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='dpi',
            field=models.CharField(blank=True, max_length=13, verbose_name='N\xba DPI'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='escuela_vac_ant',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2, verbose_name='Ha solicitado anteriormente escuela de vacaciones'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='escuela_vac_ant_curso',
            field=models.CharField(blank=True, max_length=100, verbose_name='Si es positiva la respuesta, \xbfEn qu\xe9 curso se le otorg\xf3 la beca'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='escuela_vac_ant_fecha',
            field=models.CharField(blank=True, max_length=10, verbose_name='En que fecha se otorg\xf3 la beca'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='estudios_completos',
            field=models.CharField(blank=True, choices=[('licenciatura', 'Licenciatura'), ('especialidad', 'Especialidad'), ('maestr\xeda', 'Maestr\xeda'), ('doctorado', 'Doctorado')], max_length=12, verbose_name='Estudios completos de:'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='exp_lab',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2, verbose_name='Posee experiencia laboral'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=9, verbose_name='G\xe9nero'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='laboratorio',
            field=models.CharField(blank=True, choices=[('si', 'S\xed'), ('no', 'No')], max_length=2, verbose_name='\xbfSu curso lleva Laboratorio'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='lugar_trabajo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_carne',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N\xba carn\xe9'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_colegiado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N\xba colegido'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_hermanos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N\xba de hermanos'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='n_reg_personal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='N\xba registro personal'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='niv_ingl',
            field=models.CharField(blank=True, choices=[('basico', 'B\xe1sico'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], max_length=10, verbose_name='Nivel de ingl\xe9s fuera de CALUSAC'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='nombre_curso_1',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nombre del curso 1'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='nombre_curso_2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nombre del curso 2'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=20, verbose_name='N\xba Pasaporte'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='profesion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Profesi\xf3n'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='recibe_ayuda',
            field=models.CharField(blank=True, max_length=100, verbose_name='\xbfRecibe alguna ayuda econ\xf3mica extra?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='secc_curso_1',
            field=models.CharField(blank=True, max_length=300, verbose_name='Secci\xf3n del curso 1'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='secc_curso_2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Secci\xf3n del curso 2'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='sosten_estudios',
            field=models.CharField(blank=True, max_length=100, verbose_name='\xbfQui\xe9n sostiene sus estudios?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='tit_acred',
            field=models.CharField(blank=True, max_length=100, verbose_name='T\xedtulo que acredita'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='trabaja_ing',
            field=models.BooleanField(default=False, verbose_name='\xbfTrabaja en Ingenier\xeda?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='trabaja_usac',
            field=models.BooleanField(default=False, verbose_name='\xbfTrabaja en USAC?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='trabaja_usac_lugar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Si trabaja en la USAC, \xbfD\xf3nde?'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='trabajo_padres',
            field=models.CharField(blank=True, max_length=300, verbose_name='\xbfEn qu\xe9 trabajan los padres'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='transporte',
            field=models.CharField(blank=True, choices=[('vehiculo', 'Vehiculo'), ('bus', 'Bus'), ('moto', 'Moto'), ('a pie', 'A Pie')], max_length=20, verbose_name='Transporte a la universidad'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='unidad_trabajo',
            field=models.CharField(blank=True, max_length=300, verbose_name='Unidad de trabajo'),
        ),
        migrations.AlterField(
            model_name='datos_beca',
            name='zona_vive',
            field=models.CharField(blank=True, max_length=100, verbose_name='En que zona vive'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='noticias.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='experience',
            field=models.FileField(upload_to='experiences', verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='name_student',
            field=models.CharField(max_length=250, verbose_name='Nombre de estudiante'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='thesis',
            field=models.FileField(upload_to='thesis', verbose_name='Tesis'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='noticias.Universidad', verbose_name='Universidad'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='noticias.Anho', verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='anho',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='A\xf1o'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='apoyo_familiar',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfQui\xe9nes apoyan al ingreso familiar?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='beneficiado',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Fue beneficiad@'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='calusac',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfHa estudiado en CALUSAC?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='calusac_ult_niv',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Nivel CALUSAC'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='carrera',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='casa',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Su casa es:'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='conv_ant',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Ha participado en convocatorias anteriores'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='conv_ant_cual',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Indicar cuales (Si aplica):'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='conv_ant_exp',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Explicar en que consistia:'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='creditos',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Cr\xe9ditos'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='departamento_vive',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='En que departamento vive'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='dpi',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='N\xba DPI'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='edad',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='escuela_vac_ant',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Ha solicitado anteriormente escuela de vacaciones'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='escuela_vac_ant_curso',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Si es positiva la respuesta, \xbfEn qu\xe9 curso se le otorg\xf3 la beca'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='escuela_vac_ant_fecha',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='En que fecha se otorg\xf3 la beca'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estudios_completos',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Estudios completos de:'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='exp_lab',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Posee experiencia laboral'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='genero',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='G\xe9nero'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='laboratorio',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfSu curso lleva Laboratorio'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='lugar_trabajo',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_carne',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='N\xba carnet'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_colegiado',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='N\xba colegiado'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_hermanos',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='N\xba de hermanos'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='n_reg_personal',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='N\xba registro personal'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='name_form',
            field=models.CharField(max_length=100, verbose_name='Nombre del formulario'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='niv_ingl',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Nivel de ingl\xe9s fuera de CALUSAC'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_completo',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_curso_1',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Nombre del curso 1'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_curso_2',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Nombre del curso 2'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='pasaporte',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='N\xba Pasaporte'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='profesion',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Profesi\xf3n'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='promedio',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Promedio'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='recibe_ayuda',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfRecibe alguna ayuda econ\xf3mica extra?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='secc_curso_1',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Secci\xf3n del curso 1'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='secc_curso_2',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Secci\xf3n del curso 2'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='sosten_estudios',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfQui\xe9n sostiene sus estudios?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='status',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tit_acred',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='T\xedtulo que acredita'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabaja_ing',
            field=models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfTrabaja en Ingenier\xeda?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabaja_usac',
            field=models.CharField(choices=[('si', 'S\xed'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfTrabaja en USAC?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabaja_usac_lugar',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Si trabaja en la USAC, \xbfD\xf3nde?'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='trabajo_padres',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='\xbfEn qu\xe9 trabajan los padres'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='transporte',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Transporte a la universidad'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='unidad_trabajo',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='Unidad de trabajo'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='zona_vive',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='no', max_length=10, verbose_name='En que zona vive'),
        ),
        migrations.AlterField(
            model_name='masinfo',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='t_beca',
            name='type',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=13, verbose_name='\xc1mbito de la beca'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='noticias.Pais', verbose_name='Pa\xeds'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
