# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0043_auto_20160418_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='Requerido', max_length=10, verbose_name='E-mail'),
        ),
    ]
