# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0044_auto_20160419_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='dpi',
            field=models.CharField(default='Requerido', max_length=10, verbose_name='N\xba DPI'),
        ),
    ]
