# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0045_auto_20160419_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='dpi',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='requerido', max_length=10, verbose_name='N\xba DPI'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.CharField(choices=[('requerido', 'Requerido'), ('opcional', 'Opcional'), ('no', 'No')], default='requerido', max_length=10, verbose_name='E-mail'),
        ),
    ]
