# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0046_auto_20160419_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='thesis',
            field=models.FileField(blank=True, null=True, upload_to='thesis', verbose_name='Tesis'),
        ),
    ]
